# Exploratory Data Analysis

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os, json, re

In [5]:
df = pd.read_json('./data/all_races.json')

In [6]:
df.head()

,Unnamed: 0,actual_wt,date,declared_wt,draw,finish_time,going,horse_id,horse_name,horse_no,jockey_name,lbw,plc,public_odds,race_dist,race_id,race_no,race_type,running_pos,trainer_name
0,0,120,2019-12-29,1066,5,1:22.73,GOOD,C413,RICH_AND_LUCKY,2.0,Z Purton,-,1,1.7,1400,284,RACE_1,RESTRICTED_RACE,3 4 3 1,L Ho
1,1,120,2019-12-29,1078,4,1:22.87,GOOD,C437,KING_DRAGON,7.0,S de Sousa,3/4,2,11,1400,284,RACE_1,RESTRICTED_RACE,2 2 1 2,K L Man
2,2,120,2019-12-29,1297,1,1:22.97,GOOD,D091,INVALUABLE,6.0,C Schofield,1-1/2,3,6.3,1400,284,RACE_1,RESTRICTED_RACE,6 6 7 3,R Gibson
3,3,120,2019-12-29,1087,3,1:23.24,GOOD,C419,KELMIMI_WINS,8.0,A Badel,3-1/4,4,26,1400,284,RACE_1,RESTRICTED_RACE,5 7 5 4,C H Yip
4,4,120,2019-12-29,1022,2,1:23.51,GOOD,C342,VICTORY_FOR_ALL,5.0,T H So,5,5,147,1400,284,RACE_1,RESTRICTED_RACE,4 3 4 5,Y S Tsui